// <auto-generated />
using System;
using ChequeClearingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChequeClearingService.Migrations
{
    [DbContext(typeof(ChequeClearingDbContext))]
    partial class ChequeClearingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChequeClearingService.Models.Cheque", b =>
                {
                    b.Property<int>("ChequeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChequeId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ChequeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClearedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ClearingBatchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayeeName")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChequeId");

                    b.HasIndex("ClearingBatchId");

                    b.ToTable("Cheques");
                });

            modelBuilder.Entity("ChequeClearingService.Models.ClearingBatch", b =>
                {
                    b.Property<int>("ClearingBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClearingBatchId"));

                    b.Property<DateTime>("BatchDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClearingBatchId");

                    b.ToTable("ClearingBatches");
                });

            modelBuilder.Entity("ChequeClearingService.Models.Cheque", b =>
                {
                    b.HasOne("ChequeClearingService.Models.ClearingBatch", null)
                        .WithMany("Cheques")
                        .HasForeignKey("ClearingBatchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChequeClearingService.Models.ClearingBatch", b =>
                {
                    b.Navigation("Cheques");
                });
#pragma warning restore 612, 618
        }
    }
}
