// <auto-generated />
using System;
using AccountService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountService.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    [Migration("20260407022608_AddDepositFields")]
    partial class AddDepositFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountService.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("AccruedInterest")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AccruedTDS")
                        .HasColumnType("numeric");

                    b.Property<string>("ApprovalStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyDocuments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DailyTransactionLimit")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitialDepositMode")
                        .HasColumnType("text");

                    b.Property<decimal?>("InstallmentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsBSBD")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMinor")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSimplifiedKYC")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSpecialScheme")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTDSExempt")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("JointCustomers")
                        .HasColumnType("integer[]");

                    b.Property<string>("LegalGuardianName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MaturityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MinorAccountLimit")
                        .HasColumnType("numeric");

                    b.Property<string>("ModeOfOperation")
                        .HasColumnType("text");

                    b.Property<string>("OldAccountNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OldAccountOpenedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PrematureClosurePenalty")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("SpecialSchemeName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int?>("TermMonths")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TransactionLimit")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("WorkflowInstanceId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Accounts", "public");
                });

            modelBuilder.Entity("AccountService.Models.AccountHistory", b =>
                {
                    b.Property<int>("AccountHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountHistoryId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AccountHistoryId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountHistories", "public");
                });

            modelBuilder.Entity("AccountService.Models.AccountProductType", b =>
                {
                    b.Property<int>("AccountProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountProductTypeId"));

                    b.Property<string>("AllowedCustomerTypes")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinimumOpeningAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("AccountProductTypeId");

                    b.ToTable("AccountProductTypes", "public");
                });

            modelBuilder.Entity("AccountService.Models.AccountRestriction", b =>
                {
                    b.Property<int>("AccountRestrictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountRestrictionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RestrictionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AccountRestrictionId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountRestrictions", "public");
                });

            modelBuilder.Entity("AccountService.Models.Nominee", b =>
                {
                    b.Property<int>("NomineeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NomineeId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizedReceiver")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("PercentageShare")
                        .HasColumnType("numeric");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.HasKey("NomineeId");

                    b.HasIndex("AccountId");

                    b.ToTable("Nominees", "public");
                });

            modelBuilder.Entity("AccountService.Models.Passbook", b =>
                {
                    b.Property<int>("PassbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PassbookId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PassbookNumber")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("PassbookId");

                    b.ToTable("Passbooks", "public");
                });

            modelBuilder.Entity("AccountService.Models.Account", b =>
                {
                    b.HasOne("AccountService.Models.AccountProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("AccountService.Models.AccountHistory", b =>
                {
                    b.HasOne("AccountService.Models.Account", "Account")
                        .WithMany("History")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AccountService.Models.AccountRestriction", b =>
                {
                    b.HasOne("AccountService.Models.Account", "Account")
                        .WithMany("Restrictions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AccountService.Models.Nominee", b =>
                {
                    b.HasOne("AccountService.Models.Account", null)
                        .WithMany("Nominees")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccountService.Models.Account", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Nominees");

                    b.Navigation("Restrictions");
                });
#pragma warning restore 612, 618
        }
    }
}
