name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: cd saar-core-banking-services && dotnet restore ./AccountService/AccountService.csproj
    - name: Build
      run: cd saar-core-banking-services && dotnet build ./AccountService/AccountService.csproj --configuration Release --no-restore
    - name: Test
      run: cd saar-core-banking-services && dotnet test ./AccountService.Tests/AccountService.Tests.csproj --no-restore --verbosity normal
    - name: Publish
      run: cd saar-core-banking-services && dotnet publish ./AccountService/AccountService.csproj --configuration Release --no-restore --output ./publish
    - name: Docker Build
      run: cd saar-core-banking-services && docker build -t accountservice ./AccountService
